// <auto-generated />
using System;
using CalendarApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarApi.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    partial class CalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CalendarApi.Domain.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents", (string)null);
                });

            modelBuilder.Entity("CalendarApi.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CalendarApi.Domain.CalendarEvent", b =>
                {
                    b.OwnsOne("CalendarApi.Domain.RecurrencePattern", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("CalendarEventId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Count")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Interval")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("Until")
                                .HasColumnType("TEXT");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("CalendarEvents");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId");
                        });

                    b.Navigation("Recurrence");
                });
#pragma warning restore 612, 618
        }
    }
}
